# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SBAImagePickerController' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SBAImagePickerController
pod 'SBAImagePickerController', :git => 'https://github.com/shoaib-akhtar/SBAImagePickerController', :branch => 'master'
end
